protected/controllers/MahasiswaController.php
<?php

class MahasiswaController extends Controller
{
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
				'foreColor'=>0xff755a,
			),
		);
	}
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','register','captcha'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Mahasiswa;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Mahasiswa']))
		{
			$model->attributes=$_POST['Mahasiswa'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		if (!Yii::app()->user->allowEdit('mahasiswa', $id))
			throw new CHttpException(403, 'Anda tidak berhak mengedit');
			
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Mahasiswa']))
		{
			$model->attributes=$_POST['Mahasiswa'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Mahasiswa');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Mahasiswa('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Mahasiswa']))
			$model->attributes=$_GET['Mahasiswa'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Mahasiswa::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='mahasiswa-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	/**
	 * Melakukan Registrasi User untuk Mahasiswa
	 */
	public function actionRegister()
	{
	    $model=new MahasiswaForm('register');

	    if(isset($_POST['MahasiswaForm']))
	    {
        $model->attributes=$_POST['MahasiswaForm'];
        if($model->validate())
        {
          $model2 = new User;    
          $model2->scenario = 'register';
          $model2->attributes = $_POST['MahasiswaForm'];
          $model2->salt = $model2->generateSalt();
          $model2->password = $model2->hashPassword($model2->password, $model2->salt);
          $model2->role = 'mahasiswa';

          if ($model2->save()) {
          	$model3 = new Mahasiswa;
          	$model3->scenario = 'register';
          	$model3->attributes = $_POST['MahasiswaForm'];
          	$model3->id_user = $model2->id;
          	$model3->foto = CUploadedFile::getInstance($model,'foto');
						if ($model3->save()) {
							if ($model3->foto) {
								$path = getcwd().'/images/mahasiswa/'.$model3->foto;
								$model3->foto->saveAs($path);
								Yii::app()->phpThumb->makeThumb($path);
						  }
							Yii::app()->user->setFlash('success','Registrasi mahasiswa berhasil');
         			$this->redirect(array('/site/index'));
						} else {
							$model2->delete();
							throw new CHttpException(505, "Kesalahan dalam insert ".CHtml::errorSummary($model3));
						}
          } else throw new CHttpException(505, "Kesalahan dalam insert ".CHtml::errorSummary($model2));
       	}
	    }
	    $this->render('register',array('model'=>$model));
	}

}

protected/controllers/PembimbingController.php
<?php

class PembimbingController extends Controller
{
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
				'foreColor'=>0xff755a,
			),
		);
	}
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','register','captcha'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Pembimbing;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Pembimbing']))
		{
			$model->attributes=$_POST['Pembimbing'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Pembimbing']))
		{
			$model->attributes=$_POST['Pembimbing'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Pembimbing');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Pembimbing('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Pembimbing']))
			$model->attributes=$_GET['Pembimbing'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Pembimbing::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='pembimbing-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	/**
	 * Melakukan Registrasi User untuk Pembimbing
	 */
	public function actionRegister()
	{
	    $model=new PembimbingForm('register');

	    if(isset($_POST['PembimbingForm']))
	    {
        $model->attributes=$_POST['PembimbingForm'];
        if($model->validate())
        {
          $model2 = new User;    
          $model2->scenario = 'register';
          $model2->attributes = $_POST['PembimbingForm'];
          $model2->salt = $model2->generateSalt();
          $model2->password = $model2->hashPassword($model2->password, $model2->salt);
          $model2->role = 'pembimbing';

          if ($model2->save()) {
          	$model3 = new Pembimbing;
          	$model3->scenario = 'register';
          	$model3->attributes = $_POST['PembimbingForm'];
          	$model3->id_user = $model2->id;
          	$model3->foto = CUploadedFile::getInstance($model,'foto');
						if ($model3->save()) {
							if ($model3->foto) {
								$path = getcwd().'/images/pembimbing/'.$model3->foto;
								$model3->foto->saveAs($path);
								Yii::app()->phpThumb->makeThumb($path);
						  }
							Yii::app()->user->setFlash('success','Registrasi pembimbing berhasil');
         			$this->redirect(array('/site/index'));
						} else {
							$model2->delete();
							throw new CHttpException(505, "Kesalahan dalam insert ".CHtml::errorSummary($model3));
						}
          } else throw new CHttpException(505, "Kesalahan dalam insert ".CHtml::errorSummary($model2));
       	}
	    }
	    $this->render('register',array('model'=>$model));
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/main-vivi.php
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>ARTA : Arsip Tugas Akhir</title>
	<style>
          body { background: black; }
          .media {background : black;}
    </style>
	<link rel="stylesheet" href="<?php echo Yii::app()->baseUrl ?>/css/bootstrap.css">

	
	<div class="media" >
		<a class="pull-left" href="#">
		<?php echo CHtml::image(Yii::app()->request->baseUrl . '/img/arta.png') ?>
		</a>
		<div class="media" style="margin-top:50px">
			<h5 class="media-heading"> <font color="white" face="century gothic">Repository Tugas Akhir Mahasiswa Informatika Institut Teknologi Bandung</font></h5>
		</div>
		<div class="media">
					<ul id="myTab" class="nav nav-tabs bwh stripb">
					<li><a href="<?php echo Yii::app()->createUrl('/site/index') ?>" data-toggle="tab"><i class="icon-home"></i> Home</a></li>
					<li><a href="#arsip" data-toggle="tab"><i class="icon-folder-open"></i> Arsip</a></li>
					<li><a href="#profile" data-toggle="tab"><i class="icon-eye-open"></i> Profile</a></li>
					<li><a href="<?php echo Yii::app()->createUrl('/site/about') ?>" data-toggle="tab"><i class="icon-hand-left"></i> About Us</a></li>
					<li><a href="<?php echo Yii::app()->createUrl('/site/contact') ?>" data-toggle="tab"><i class="icon-envelope"></i> Contact</a></li>
					<li><a href="<?php echo Yii::app()->createUrl('/site/login') ?>" data-toggle="tab"><i class="icon-user"></i> Login</a></li>
            </ul>
		</div>
	</div>
				
	
	
	
	<div class="strip" style="margin-top:30px">
      <div class="container">
          <div class="full-search-bar" align="right">
            <form class="form-search">
				<input type="text" class="input-medium search-query">
				<button type="submit" class="btn btn-info"><i class="icon-search"></i>Pencarian Tugas Akhir</button>
			</form>
          </div>  
		 </div>
	</div>
	
</head>
<body>
	
		<div class="container">
			<div id="content">
				<?php echo $content; ?>
			</div><!-- content -->
		</div>
	
	
</body>
<footer class="footer">
  <div class="media" style="margin-top:50px">
			<h5 class="media-heading" style="margin-top:50px"> <font color="white" face="century gothic">ARTA, Arsip Tugas Akhir &copy; Basis Data 2013.</font></h5>
	</div>
</footer>
</html>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

		 <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->baseUrl; ?>/css/styles.css" />
		 
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->baseUrl; ?>/css/bootstrap.css" />

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->baseUrl; ?>/css/bootstrap-responsive.css" />
		
	<title><?php echo CHtml::encode($this->pageTitle); ?></title>

</head>

<body>
<?php $this->widget('bootstrap.widgets.TbNavbar',array(
		'type'=>'inverse',
		'brand'=>'Arta',
    'items'=>array(
    		$this->renderPartial('//layouts/search-form', null, true),
    // 		array(
    //     	'class'=>'bootstrap.widgets.TbMenu',
    //     	'encodeLabel'=>false,
    //       'items'=>array(
    //       	array('label'=>' ', 'items'=>array(
				// 			array('label'=>$this->renderPartial('//layouts/search-cat', null, true)),
				// 		)),
				// 	),
				// ),
        array(
        	'class'=>'bootstrap.widgets.TbMenu',
        	'htmlOptions'=>array('class'=>'pull-right'),
        	'encodeLabel'=>false,
          'items'=>array(
          	array('label'=>'<i class="icon-book icon-white"></i> Jelajahi', 'url'=>array('/tugasakhir/index')),
          	array('label'=>'<i class="icon-plus-sign icon-white"></i> Buat Akun', 'visible'=>Yii::app()->user->isGuest, 'items'=>array(
							array('label'=>'Mahasiswa', 'url'=>array('/mahasiswa/register')),	
							array('label'=>'Pembimbing', 'url'=>array('/pembimbing/register')),	
						)),
						array('label'=>'<i class="icon-user icon-white"></i> Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
						array('label'=>Yii::app()->user->name, 'visible'=>!Yii::app()->user->isGuest, 'items'=>array(
							array('label'=>'Profile', 'url'=>Yii::app()->user->profileUrl),
							array('label'=>'Logout', 'url'=>array('/site/logout')),	
						)),
					),
				),
    ),
)); ?>
<div class="container" id="page">

	<?php $this->widget('bootstrap.widgets.TbAlert'); ?>

	<?php echo $content; ?>

</div><!-- page -->

<div class="clear"></div>

<div id="footer">
	Arsip Tugas Akhir Basis Data &copy; <?php echo date('Y'); ?>
</div><!-- footer -->

</body>
</html>

protected/views/layouts/search-cat.php
<?php 
$arr[0] = 'Judul';
$arr[1] = 'Penulis';
$arr[2] = 'Pembimbing';
$value = isset($_GET['cat']) ? $_GET['cat'] : '';
echo CHtml::dropDownList('cat', $value, $arr, array('id'=>'cat', 'onchange'=>'this.form.submit()', 'style'=>'width:120px'));
?>
<script type="text/javascript">
$(function(){
	$('.dropdown-menu').find('#cat').click(function (e) {
	    e.stopPropagation();
	  });
});
</script>

protected/views/layouts/search-form.php
<form class="navbar-search pull-left" action="<?php echo Yii::app()->createUrl('/tugasakhir/search') ?>">
	<input type="search" class="span3" placeholder="Cari Tugas Akhir" name="q" value="<?php echo (isset($_GET['q']) ? $_GET['q'] : '') ?>" id="search">

	<?php if (isset($_GET['tag'])): ?>
		<input type="hidden" name="tag" value="<?php echo $_GET['tag'] ?>">
	<?php endif ?>
	<?php $this->renderPartial('//layouts/search-cat') ?>
</form>

<link href="<?php echo Yii::app()->baseUrl ?>/css/jquery.autocomplete.css" rel="stylesheet">

<script type="text/javascript" src="<?php echo Yii::app()->baseUrl ?>/js/jquery.autocomplete.js"></script>
<script type="text/javascript">
$(function() {
  $("#search").autocomplete('<?php echo Yii::app()->createAbsoluteUrl("/tugasakhir/search") ?>' + $("#cat").val().toString(), {
    remoteDataType: 'json', minChars: 2,
    showResult: function(value, data) {
      return "<img src=\"" + data[2] + "\" width=\"50px\" class=\"sauto\"/> <b>" + value + "</b> <br>" + data[1];
    },
    onItemSelect: function(item) {
      window.location = "<?php echo Yii::app()->createAbsoluteUrl('/tugasakhir/view/id') ?>/" + item.data[0];
    },
  });
});
</script>