protected/models/Mahasiswa.php
<?php

/**
 * This is the model class for table "mahasiswa".
 *
 * The followings are the available columns in table 'mahasiswa':
 * @property integer $id
 * @property string $nama
 * @property string $nim
 * @property string $foto
 *
 * The followings are the available model relations:
 * @property Tugasakhir[] $tugasakhirs
 */
class Mahasiswa extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Mahasiswa the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'mahasiswa';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nama, nim', 'required'),
			array('nama, foto', 'length', 'max'=>128),
			array('nim', 'length', 'max'=>15),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, nama, nim, foto', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'tugasakhir' => array(self::HAS_MANY, 'Tugasakhir', 'id_mahasiswa'),
			'user' => array(self::BELONGS_TO, 'User', 'id_user'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'nama' => 'Nama',
			'nim' => 'Nim',
			'foto' => 'Foto',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('nama',$this->nama,true);
		$criteria->compare('nim',$this->nim,true);
		$criteria->compare('foto',$this->foto,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	/**
   * Mengambil profile picuture user
  */
  public function getProfilePicture() {
      return Yii::app()->baseUrl.'/images/mahasiswa/'.$this->foto;
  }
}

protected/models/MahasiswaForm.php
<?php
/**
 * Register form model
 */
class MahasiswaForm extends CFormModel
{
	public $username;
	public $password;
	public $password2;
	public $email;
	public $nama;
	public $nim;
	public $foto;
	public $verifyCode;
	
	public function rules()
	{
		return array(
			array('username', 'match', 'allowEmpty' => false, 'pattern' => '/[A-Za-z0-9\x80-\xFF]+$/'),
			array('username', 'length', 'max'=>50),
			array('email', 'email'),
			array('email, username', 'unique', 'className' => 'User' ),
			array('username, password, password2, email, nama, nim', 'required'),
			array('nama', 'length', 'max'=>100),
			array('username, password, password2', 'length', 'min' => 6, 'max' => 32),
			array('password2', 'compare', 'compareAttribute'=>'password'),
			array('email', 'length', 'min' => 3, 'max' => 55),
			array('foto', 'file', 'allowEmpty' => true, 'types' => 'jpg,jpeg,gif,png', 'maxSize' => 1024 * 1024 * 2),
			array('verifyCode', 'captcha', 'allowEmpty'=>!CCaptcha::checkRequirements()),
		);
	}
	
	/**
	 * Attribute values
	 *
	 * @return array
	 */
	public function attributeLabels()
	{
		return array(
			'username' => 'Username',
			'password' => 'Password',
			'password2' => 'Ulangi Password',
			'email' => 'Email',
			'nama' => 'Nama',
			'nim' => 'NIM',
			'picture' => 'Foto',
		);
	}
	
}

protected/controllers/MahasiswaController.php
<?php

class MahasiswaController extends Controller
{
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
				'foreColor'=>0xff755a,
			),
		);
	}
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','register','captcha'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Mahasiswa;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Mahasiswa']))
		{
			$model->attributes=$_POST['Mahasiswa'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		if (!Yii::app()->user->allowEdit('mahasiswa', $id))
			throw new CHttpException(403, 'Anda tidak berhak mengedit');
			
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Mahasiswa']))
		{
			$model->attributes=$_POST['Mahasiswa'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Mahasiswa');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Mahasiswa('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Mahasiswa']))
			$model->attributes=$_GET['Mahasiswa'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Mahasiswa::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='mahasiswa-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	/**
	 * Melakukan Registrasi User untuk Mahasiswa
	 */
	public function actionRegister()
	{
	    $model=new MahasiswaForm('register');

	    if(isset($_POST['MahasiswaForm']))
	    {
        $model->attributes=$_POST['MahasiswaForm'];
        if($model->validate())
        {
          $model2 = new User;    
          $model2->scenario = 'register';
          $model2->attributes = $_POST['MahasiswaForm'];
          $model2->salt = $model2->generateSalt();
          $model2->password = $model2->hashPassword($model2->password, $model2->salt);
          $model2->role = 'mahasiswa';

          if ($model2->save()) {
          	$model3 = new Mahasiswa;
          	$model3->scenario = 'register';
          	$model3->attributes = $_POST['MahasiswaForm'];
          	$model3->id_user = $model2->id;
          	$model3->foto = CUploadedFile::getInstance($model,'foto');
						if ($model3->save()) {
							if ($model3->foto) {
								$path = getcwd().'/images/mahasiswa/'.$model3->foto;
								$model3->foto->saveAs($path);
								Yii::app()->phpThumb->makeThumb($path);
						  }
							Yii::app()->user->setFlash('success','Registrasi mahasiswa berhasil');
         			$this->redirect(array('/site/index'));
						} else {
							$model2->delete();
							throw new CHttpException(505, "Kesalahan dalam insert ".CHtml::errorSummary($model3));
						}
          } else throw new CHttpException(505, "Kesalahan dalam insert ".CHtml::errorSummary($model2));
       	}
	    }
	    $this->render('register',array('model'=>$model));
	}

}

protected/views/mahasiswa/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array( 
    'id'=>'mahasiswa-form', 
    'enableClientValidation'=>true,
		'clientOptions'=>array(
			'validateOnSubmit'=>true,
		),
)); ?>

    <?php echo $form->errorSummary($model); ?>

    <?php echo $form->textFieldRow($model,'nama',array('class'=>'span5','maxlength'=>128)); ?>

    <?php echo $form->textFieldRow($model,'nim',array('class'=>'span5','maxlength'=>15)); ?>

    <div class="form-actions"> 
        <?php $this->widget('bootstrap.widgets.TbButton', array( 
            'buttonType'=>'submit', 
            'type'=>'primary', 
            'label'=>$model->isNewRecord ? 'Create' : 'Simpan', 
        )); ?>
    </div> 

<?php $this->endWidget(); ?>

protected/views/mahasiswa/_search.php
<?php
/* @var $this MahasiswaController */
/* @var $model Mahasiswa */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'nama'); ?>
		<?php echo $form->textField($model,'nama',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'nim'); ?>
		<?php echo $form->textField($model,'nim',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'foto'); ?>
		<?php echo $form->textField($model,'foto',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/mahasiswa/_view.php
<?php
/* @var $this MahasiswaController */
/* @var $data Mahasiswa */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nama')); ?>:</b>
	<?php echo CHtml::encode($data->nama); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nim')); ?>:</b>
	<?php echo CHtml::encode($data->nim); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('foto')); ?>:</b>
	<?php echo CHtml::encode($data->foto); ?>
	<br />


</div>

protected/views/mahasiswa/admin.php
<?php
/* @var $this MahasiswaController */
/* @var $model Mahasiswa */

$this->breadcrumbs=array(
	'Mahasiswas'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Mahasiswa', 'url'=>array('index')),
	array('label'=>'Create Mahasiswa', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('mahasiswa-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Mahasiswas</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'mahasiswa-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'nama',
		'nim',
		'foto',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/mahasiswa/create.php
<h1>Create Mahasiswa</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/mahasiswa/index.php
<?php
/* @var $this MahasiswaController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Mahasiswas',
);

$this->menu=array(
	array('label'=>'Create Mahasiswa', 'url'=>array('create')),
	array('label'=>'Manage Mahasiswa', 'url'=>array('admin')),
);
?>

<h1>Mahasiswas</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/mahasiswa/register.php
<?php
/* @var $this MahasiswaFormController */
/* @var $model MahasiswaForm */
/* @var $form CActiveForm */
?>
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<h1>Daftar Mahasiswa</h1>
		<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
			'id'=>'mahasiswa-form-register-form',
			'enableClientValidation'=>true,
			'clientOptions'=>array(
				'validateOnSubmit'=>true,
			),
			'htmlOptions' => array('enctype' => 'multipart/form-data'),
		)); ?>

			<?php //echo $form->errorSummary($model); ?>

				<?php echo $form->textFieldRow($model,'username', array('class'=>'input-block-level')); ?>

				<?php echo $form->textFieldRow($model,'email', array('class'=>'input-block-level')); ?>

				<?php echo $form->passwordFieldRow($model,'password', array('class'=>'input-block-level')); ?>

				<?php echo $form->passwordFieldRow($model,'password2', array('class'=>'input-block-level')); ?>

				<?php echo $form->textFieldRow($model,'nama', array('class'=>'input-block-level')); ?>

				<?php echo $form->textFieldRow($model,'nim', array('class'=>'input-block-level')); ?>

				<?php echo $form->fileFieldRow($model,'foto'); ?>
				

				<?php if(CCaptcha::checkRequirements()): ?>
					<?php echo $form->captchaRow($model,'verifyCode'); ?>
				<?php endif; ?>

				<div class="form-actions">
					<?php $this->widget('bootstrap.widgets.TbButton',array(
			            'buttonType'=>'submit',
			            'type'=>'primary',
			            'size'=>'large',
			            'label'=>'Daftar',
			        )); ?>
				</div>

		<?php $this->endWidget(); ?>
		</div>
	</div>	
</div>

protected/views/mahasiswa/update.php
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<h1>Edit Profil Mahasiswa</h1>
			<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
		</div>
	</div>
</div>

protected/views/mahasiswa/view.php
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<h1 style="text-align:center">Profile</h1>
			
			<div style="margin:20px; text-align:center">
				<?php echo CHtml::image($model->profilePicture) ?>
			</div>

			<?php $this->widget('bootstrap.widgets.TbDetailView', array(
				'data'=>$model,
				'attributes'=>array(
					'nama',
					'nim',
					array(
					  'label'=>'email',
					  'value'=>$model->user->email,
					),
				),
			)); ?>
			
			<?php if (Yii::app()->user->allowEdit('mahasiswa', $model->id)): ?>
				<?php echo CHtml::link('Edit Profil', array('update', 'id'=>$model->id), array('class'=>'btn')) ?>
			<?php endif ?>
		</div>
	</div>
</div>