protected/models/Tugasakhir.php
<?php

/**
 * This is the model class for table "tugasakhir".
 *
 * The followings are the available columns in table 'tugasakhir':
 * @property integer $id
 * @property integer $id_mahasiswa
 * @property string $judul
 * @property integer $tahun
 * @property string $abstrak
 * @property string $deskripsi
 * @property string $timestamp
 * @property string $link
 * @property string $poster
 * @property integer $download
 *
 * The followings are the available model relations:
 * @property PembimbingTugasakhir[] $pembimbingTugasakhirs
 * @property TagTugasakhir[] $tagTugasakhirs
 * @property Mahasiswa $idMahasiswa
 */
class Tugasakhir extends CActiveRecord
{
	public $mytag;
	public $mypembimbing;
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Tugasakhir the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tugasakhir';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('judul, tahun, abstrak, deskripsi', 'required'),
			array('id_mahasiswa, tahun, download', 'numerical', 'integerOnly'=>true),
			array('judul, link, poster', 'length', 'max'=>128),
			array('abstrak', 'length', 'max'=>255),
			array('poster', 'file', 'allowEmpty' => false, 'types' => 'jpg,jpeg,gif,png', 'maxSize' => 1024 * 800, 'on'=>'create'),
			array('link', 'file', 'allowEmpty' => false, 'types' => 'pdf', 'maxSize' => 1024 * 1024 * 5, 'on'=>'create'),
			array('poster', 'file', 'allowEmpty' => true, 'types' => 'jpg,jpeg,gif,png', 'maxSize' => 1024 * 800, 'on'=>'update'),
			array('link', 'file', 'allowEmpty' => true, 'types' => 'pdf', 'maxSize' => 1024 * 1024 * 5, 'on'=>'update'),
			array('mypembimbing', 'checkPembimbing', 'except' => 'download'),
			array('mytag', 'checkTags', 'except' => 'download'),
			array('id, id_mahasiswa, judul, tahun, abstrak, deskripsi, timestamp, link, poster, download', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'pembimbingTugasakhir' => array(self::HAS_MANY, 'pembimbingTugasakhir', 'id_tugasakhir'),
			'pembimbing' => array(self::HAS_MANY, 'Pembimbing', 'id_pembimbing', 'through'=>'pembimbingTugasakhir'),
			'tags' => array(self::MANY_MANY, 'Tag', 'tag_tugasakhir(id_tugasakhir, id_tag)'),
			'penulis' => array(self::BELONGS_TO, 'Mahasiswa', 'id_mahasiswa'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'id_mahasiswa' => 'Id Mahasiswa',
			'judul' => 'Judul',
			'tahun' => 'Tahun',
			'abstrak' => 'Abstrak',
			'deskripsi' => 'Deskripsi',
			'timestamp' => 'Timestamp',
			'link' => 'File Dokumen',
			'poster' => 'Poster',
			'download' => 'Download',
			'mytag' => 'Tag',
			'mypembimbing' => 'Pembimbing',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('id_mahasiswa',$this->id_mahasiswa);
		$criteria->compare('judul',$this->judul,true);
		$criteria->compare('tahun',$this->tahun);
		$criteria->compare('abstrak',$this->abstrak,true);
		$criteria->compare('deskripsi',$this->deskripsi,true);
		$criteria->compare('timestamp',$this->timestamp,true);
		$criteria->compare('link',$this->link,true);
		$criteria->compare('poster',$this->poster,true);
		$criteria->compare('download',$this->download);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	/**
	 * Mengembalikan URL poster untuk tugas akhir yang aktif
	 */
	public function getPosterUrl()
	{
		return Yii::app()->baseUrl.'/images/poster/'.$this->poster;
	}
	/**
	 * Mengembalikan URL link pdf untuk tugas akhir yang aktif
	 */
	public function getLinkUrl()
	{
		return Yii::app()->baseUrl.'/upload/pdf/'.$this->link;
	}
	/**
	 * Mengembalikan true jika TA ini bisa diedit
	 */
	public function allowEdit()
	{
		return (Yii::app()->user->realId == $this->penulis->id && Yii::app()->user->role == 'mahasiswa');
	}
	/**
	 * Melakukan aksi sebelum menyimpan
	 */
	protected function beforeSave()
	{
		if(parent::beforeSave())
		{
			if($this->isNewRecord)
			{
				$this->timestamp = date("Y-m-d H:i:s");
				$this->id_mahasiswa = Yii::app()->user->realId;
				$this->download = 0;
			}
			return true;
		}
		else
			return false;
	}

	public function behaviors(){
  	return array( 'CAdvancedArBehavior' => array(
    'class' => 'CAdvancedArBehavior'));
  }

	public function checkTags($mytag)
	{
		$datas = explode(',', $this->mytag);
		$hasil = array();
		foreach ($datas as $item) {
			$item = trim($item);
			if (!empty($item)) {
				$ret = Tag::model()->findByAttributes(array('nama'=>$item));
				if ($ret == null) {
					$new = new Tag;
					$new->nama = strtolower($item);
					$new->save();
					$hasil[] = $new->id;
				} else {
					if (!in_array($ret->id, $hasil))
						$hasil[] = $ret->id;
				}
			}
		}
		if (count($hasil) == 0)
			$this->addError('mytag', 'Tag harus diisi');
		else
			$this->tags = $hasil;
	}

	public function checkPembimbing($mypembimbing)
	{
		if (count($this->mypembimbing) > 3)
			$this->addError('mypembimbing', 'Dosen Pembimbing terlalu banyak maksimal 3 dosen pembimbing');
		else if (count($this->mypembimbing) == 0)
			$this->addError('mypembimbing', 'Anda harus memasukkan Dosen pembimbing minimal 1');
		// else
		// 	$this->pembimbing = $this->mypembimbing;
	}

	public function savePembimbing()
	{
		PembimbingTugasakhir::model()->deleteAll('id_tugasakhir=:i', array(':i'=>$this->id));
		foreach ($this->mypembimbing as $key => $value) {
			$model = new PembimbingTugasakhir();
			$model->id_pembimbing = $value;
			$model->id_tugasakhir = $this->id;
			$model->posisi = $key+1;
			$model->save(false);
		}
	}

	public function loadTags()
	{
		$arr = array();
    foreach ($this->tags as $data) {
      $arr[] = $data->nama;
    }
    $this->mytag = implode(', ', $arr);
	}
	public function loadPembimbing()
	{
		$arr = array();
		$model = PembimbingTugasakhir::model()->findAll('id_tugasakhir = :i order by posisi asc',array(':i'=>$this->id));
    foreach ($model as $data) {
      $arr[$data->posisi] = $data->pembimbing->id;
    }
    $this->mypembimbing = $arr;
	}
}

protected/controllers/TugasakhirController.php
<?php

class TugasakhirController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','search','tags','pembimbing','download', 'search0','search1','search2'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','delete','admin','arsip'),
				'roles'=>array('mahasiswa'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Tugasakhir('create');

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Tugasakhir']))
		{
			$model->attributes=$_POST['Tugasakhir'];
			$model->poster = CUploadedFile::getInstance($model, 'poster');
			$model->link = CUploadedFile::getInstance($model, 'link');
			if($model->save()) {
				if ($model->poster) {
					$path = getcwd().'/images/poster/'.$model->poster;
					$model->poster->saveAs($path);
					Yii::app()->phpThumb->makeThumb($path, 180, 227);
				}
				if ($model->link) {
					$path = getcwd().'/upload/pdf/'.$model->link;
					$model->link->saveAs($path);
				}
				$model->savePembimbing();
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		if (!$model->allowEdit())
			throw new CHttpException(403, 'Anda tidak berhak mengedit TA ini');
		$model->scenario = 'update';

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Tugasakhir']))
		{
			$model->attributes=$_POST['Tugasakhir'];
			if (is_object(CUploadedFile::getInstance($model, 'poster')))
				$model->poster = CUploadedFile::getInstance($model, 'poster');
			if (is_object(CUploadedFile::getInstance($model, 'link')))
				$model->link = CUploadedFile::getInstance($model, 'link');
			if($model->save()) {
				if (is_object($model->poster)) {
					$path = getcwd().'/images/poster/'.$model->poster;
					$model->poster->saveAs($path);
					Yii::app()->phpThumb->makeThumb($path, 180, 227);
				}
				if (is_object($model->link)) {
					$path = getcwd().'/upload/pdf/'.$model->link;
					$model->link->saveAs($path);
				}
				$model->savePembimbing();
				$this->redirect(array('view','id'=>$model->id));
			}
		} else {
			$model->loadTags();
			$model->loadPembimbing();
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		// if(Yii::app()->request->isPostRequest)
		// {
			// we only allow deletion via POST request
			$model = $this->loadModel($id);
			if (!$model->allowEdit())
				throw new CHttpException(403, 'Anda tidak berhak mengedit TA ini');
			$model->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
		// }
		// else
		// 	throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$cBaru = new CDbCriteria;
		$cBaru->order = 'timestamp desc';
		$cBaru->limit = 5;
		$cPopuler = new CDbCriteria;
		$cPopuler->order = 'download desc';
		$cPopuler->limit = 5;
		$data['dataTerbaru']=new CActiveDataProvider('Tugasakhir', array('criteria'=>$cBaru,'pagination'=>false));
		$data['dataTerpopuler']=new CActiveDataProvider('Tugasakhir', array('criteria'=>$cPopuler,'pagination'=>false));
		$this->render('index',$data);
	}

	/**
	 * Pencarian models.
	 */
	public function actionSearch($tag = '', $q = '', $cat = '')
	{
		$c = new CDbCriteria;
		if (!empty($tag)) {
			$c->with = 'tags';
			$c->together = true;
			$c->compare('tags.nama', $tag);
		}
		if (!empty($q)) {
			$arrayCat = array(0=>'judul',1=>'penulis.nama',2=>'pembimbing.nama');
			$exp = explode(" ", $q);
			$c->with = array('tags', 'penulis', 'pembimbing');
			$c->together = true;
			if (array_key_exists($cat, $arrayCat)) {
				foreach ($exp as $token) {
					$token = trim($token);
					if (!empty($token))
						$c->compare($arrayCat[$cat], $token, true, 'or');
				}
			}
		}
		$dataProvider=new CActiveDataProvider('Tugasakhir', array('criteria'=>$c, 'pagination'=>array('pageSize'=>8)));
		$this->render('search',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * List arsip tugas akhir yang sedang login
	 */
	public function actionArsip()
	{
		$c = new CDbCriteria;
		$c->compare('id_mahasiswa', Yii::app()->user->realId);
		$dataProvider=new CActiveDataProvider('Tugasakhir', array('criteria'=>$c, 'pagination'=>array('pageSize'=>8)));
		$this->render('arsip',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Tugasakhir('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Tugasakhir']))
			$model->attributes=$_GET['Tugasakhir'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Tugasakhir::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='tugasakhir-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	public function actionTags($q)
	{
		$model = Tag::model()->findAll('nama like :q', array(':q'=>strtolower($q)."%"));
		$arr = array();
		foreach ($model as $item) {
			$arr[] = $item->nama;
		}
		echo json_encode($arr);
	}

	public function actionPembimbing($q)
	{
		$model = Pembimbing::model()->findAll('nama like :q', array(':q'=>"%".strtolower($q)."%"));
		$arr = array();
		foreach ($model as $item) {
			$arr[] = $item->nama;
		}
		echo json_encode($arr);
	}

	public function actionSearch0($q)
	{
		$model = Tugasakhir::model()->findAll('judul like :q', array(':q'=>"%".strtolower($q)."%"));
		$arr = array();
		foreach ($model as $item) {
			$arr[] = array($item->judul, $item->id, $item->penulis->nama, $item->posterUrl);
		}
		echo json_encode($arr);
	}
	public function actionSearch1($q)
	{
		$model = Tugasakhir::model()->with('penulis')->findAll('penulis.nama like :q', array(':q'=>"%".strtolower($q)."%"));
		$arr = array();
		foreach ($model as $item) {
			$arr[] = array($item->judul, $item->id, $item->penulis->nama, $item->posterUrl);
		}
		echo json_encode($arr);
	}
	public function actionSearch2($q)
	{
		$model = Tugasakhir::model()->with('pembimbing')->findAll('pembimbing.nama like :q', array(':q'=>"%".strtolower($q)."%"));
		$arr = array();
		foreach ($model as $item) {
			$arr[] = array($item->judul, $item->id, $item->penulis->nama, $item->posterUrl);
		}
		echo json_encode($arr);
	}
	public function actionDownload($id)
	{
		$model = $this->loadModel($id);
		$model->setScenario('download');
		$model->download++;
		if (!$model->save())
			throw new CHttpException(403, CHtml::errorSummary($model));
		$this->redirect(Yii::app()->createAbsoluteUrl('/upload/pdf/'.$model->link));
	}
}

protected/views/tugasakhir/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'tugasakhir-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
	'htmlOptions' => array('enctype' => 'multipart/form-data'),
)); ?>
	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldRow($model,'judul',array('class'=>'input-block-level','maxlength'=>128)); ?>

	<?php echo $form->textFieldRow($model,'tahun',array('class'=>'input-block-level')); ?>

	<?php echo $form->textFieldRow($model,'abstrak',array('class'=>'input-block-level','maxlength'=>255)); ?>

	<?php echo $form->textAreaRow($model,'deskripsi',array('rows'=>6, 'cols'=>50, 'class'=>'input-block-level')); ?>

	<?php echo $form->fileFieldRow($model,'link',array('class'=>'input-block-level','maxlength'=>128)); ?>

	<?php echo $form->fileFieldRow($model,'poster',array('class'=>'input-block-level','maxlength'=>128)); ?>

	<?php echo $form->textFieldRow($model,'mytag',array('class'=>'input-block-level','id'=>'mytag')); ?>

	<?php echo $form->dropDownListRow($model,'mypembimbing',CHtml::listData(Pembimbing::model()->findAll(), 'id', 'nama'),array('class'=>'input-block-level', 'id'=>'mypembimbing', 'multiple'=>'multiple')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Tambah' : 'Simpan',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

<div class="clear"></div>

<link href="<?php echo Yii::app()->baseUrl ?>/css/jquery.autocomplete.css" rel="stylesheet">

<link href="<?php echo Yii::app()->baseUrl ?>/css/jquery-ui.css" rel="stylesheet">
<link href="<?php echo Yii::app()->baseUrl ?>/css/jquery.bsmselect.css" rel="stylesheet">



<script type="text/javascript" src="<?php echo Yii::app()->baseUrl ?>/js/jquery.autocomplete.js"></script>

<script type="text/javascript" src="<?php echo Yii::app()->baseUrl ?>/js/jquery-ui.js"></script>
<script type="text/javascript" src="<?php echo Yii::app()->baseUrl ?>/js/jquery.bsmselect.js"></script>
<script type="text/javascript" src="<?php echo Yii::app()->baseUrl ?>/js/jquery.bsmselect.sortable.js"></script>

<script type="text/javascript">
$(function() {
 	 var last_valid_selection = null;

  $("#mytag").autocomplete("<?php echo Yii::app()->createAbsoluteUrl('tugasakhir/tags') ?>", {
    remoteDataType: 'json', minChars: 1, useDelimiter: true
  });

 //  $(".chzn-select").chosen({ max_selected_options: 3 });
 
	// var ret = [];
 //  $(".chzn-select").find('.search-choice').each(function(){
 //    var selectedValue = $(this).find('span').text();
 //    ret.push(selectedValue);  
 //    console.log(selectedValue);
 //  });
	$("#mypembimbing").bsmSelect({
	  showEffect: function($el){ $el.fadeIn(); },
	  hideEffect: function($el){ $el.fadeOut(function(){ $(this).remove();}); },
	  plugins: [$.bsmSelect.plugins.sortable()],
	  title: 'Pilih Dosen Pembimbing',
	  highlight: 'highlight',
	  addItemTarget: 'original',
	  removeLabel: '<strong>X</strong>',
	  containerClass: 'bsmContainer',                // Class for container that wraps this widget
	  listClass: 'bsmList-custom',                   // Class for the list ($ol)
	  listItemClass: 'bsmListItem-custom',           // Class for the <li> list items
	  listItemLabelClass: 'bsmListItemLabel-custom', // Class for the label text that appears in list items
	  removeClass: 'bsmListItemRemove-custom',       // Class given to the "remove" link
	  extractLabel: function($o) {return $o.html();}
	});
});
</script>

protected/views/tugasakhir/_view.php
<div class="item span3">
	<div class="well">
		<?php echo CHtml::image($data->posterUrl) ?>
		<h5><?php echo CHtml::link($data->judul, array('/tugasakhir/view', 'id'=>$data->id)) ?></h5>
		<?php echo CHtml::link($data->penulis->nama, array('/mahasiswa/view', 'id'=>$data->penulis->id)) ?>
		<p><?php echo $data->abstrak ?></p>
		<?php $mywaktu=new waktu; ?>
		<p>
			<span class="help-inline"><?php echo $mywaktu->nicetime($data->timestamp); ?></span>
			<span style="float:right"><i class="icon icon-arrow-down"></i> <?php echo $data->download ?></span>
		</p>
	
		<?php if ($data->allowEdit()): ?>
			<?php echo CHtml::link('Edit', array('/tugasakhir/update','id'=>$data->id), array('class'=>'btn')) ?> 
			<?php echo CHtml::link('Hapus', array('/tugasakhir/delete','id'=>$data->id), array('class'=>'btn')) ?>
		<?php endif ?>

	</div>
</div>

protected/views/tugasakhir/barIndex.php
<div class="well">
	<h2 style="text-align:center">Menu</h2>
<?php $this->widget('bootstrap.widgets.TbMenu', array(
  'type'=>'tabs', // '', 'tabs', 'pills' (or 'list')
  'stacked'=>true, // whether this is a stacked menu
  'encodeLabel'=>false,
  'items'=>array(
      array('label'=>'Home', 'url'=>array('/tugasakhir/index')),
      array('label'=>'Pencarian', 'url'=>array('/tugasakhir/search')),
      array('label'=>'Arsip Saya', 'url'=>array('/tugasakhir/arsip'), 'visible'=>Yii::app()->user->checkAccess('mahasiswa')),
      array('label'=>'<i class="icon icon-plus-sign"></i> Tambah', 'url'=>array('/tugasakhir/create'), 'visible'=>Yii::app()->user->checkAccess('mahasiswa')),
  ),
)); ?>
</div>

<div class="well">
  <h2 style="text-align:center">Tag</h2>
  <?php $this->renderPartial('tag') ?>
</div>

protected/views/tugasakhir/barView.php
<div class="well">
	<h2 style="text-align:center">Menu</h2>
<?php $this->widget('bootstrap.widgets.TbMenu', array(
  'type'=>'tabs', // '', 'tabs', 'pills' (or 'list')
  'stacked'=>true, // whether this is a stacked menu
  'encodeLabel'=>false,
  'items'=>array(
      array('label'=>'Download <span class="badge">'.$model->download.'</span>', 'url'=>array('/tugasakhir/download', 'id'=>$model->id)),
      
  ),
)); ?>
  <?php if ($model->allowEdit()): ?>
      <?php echo CHtml::link('Edit', array('update','id'=>$model->id), array('class'=>'btn')) ?> 
      <?php echo CHtml::link('Hapus', array('delete','id'=>$model->id), array('class'=>'btn')) ?>
    <?php endif ?>
</div>

<div class="well" style="text-align:center">
  <?php echo CHtml::image($model->penulis->profilePicture, null, array('width'=>60)) ?>
  <h4><?php echo CHtml::link($model->penulis->nama, array('/mahasiswa/view', 'id'=>$model->penulis->id)) ?></h4>
  <p class="help-block">
    <?php echo $model->penulis->nim ?> <br/>
    <?php $mywaktu=new waktu; ?>
    <?php echo $mywaktu->nicetime($model->timestamp) ?> <br/>
    <?php echo $model->tahun ?>
  </p>
</div>

<div class="well">
  <h4>Dosen Pembimbing</h4>
  <table class="table">
    <?php 
    $bim = PembimbingTugasakhir::model()->findAll('id_tugasakhir = :i order by posisi asc',array(':i'=>$model->id));
     ?>
    <?php foreach ($bim as $item): ?>
      <tr>
        <td><?php echo $item->posisi ?>.</td>
        <td><?php echo CHtml::image($item->pembimbing->profilePicture, null, array('width'=>30)) ?></td>
        <td><?php echo CHtml::link($item->pembimbing->nama, array('/pembimbing/view', 'id'=>$item->pembimbing->id)) ?></td>
      </tr>  
    <?php endforeach ?>
  </table>
</div>

protected/views/tugasakhir/create.php
<div class="row">
	<div class="span3 offset1">
		<?php $this->renderPartial('barIndex'); ?>
	</div>
	<div class="span7">
		<div class="well">
			<h1>Tambah Tugasakhir</h1>
			<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
		</div>
	</div>
</div>

protected/views/tugasakhir/tag.php
<div id="tags">
	<?php 
		$tags = Tag::model()->findAll();
		foreach ($tags as $item) {
			$url = array('/tugasakhir/search', 'tag'=>$item->nama);
			if (isset($_GET['q']))
				$url['q'] = $_GET['q'];
			if (isset($_GET['cat']))
				$url['cat'] = $_GET['cat'];
			echo CHtml::link($item->nama, $url, array('class'=>'label'));
			echo " ";
		}
	?>
</div>

protected/views/tugasakhir/view.php
<div class="row">
	<div class="span3">
		<?php $data['model'] = $model; ?>
		<?php $this->renderPartial('barView', $data); ?>
	</div>
	<div class="span9">
		<h1 class="well"><?php echo $model->judul ?></h1>
		<a class="media" href="<?php echo $model->linkUrl ?>"></a>
		<hr>
		<div class="row">
			<div class="span4">
				<div class="well">
					<h3>Abstrak</h3>
					<?php echo $model->abstrak ?>
				</div>
			</div>
			<div class="span5">
				<div class="well">
					<h3>Deskripsi</h3>
					<?php echo $model->deskripsi ?>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript" src="<?php echo Yii::app()->baseUrl ?>/js/jquery.metadata.js"></script>
<script type="text/javascript" src="<?php echo Yii::app()->baseUrl ?>/js/jquery.media.js"></script>
<script type="text/javascript">
  $(function() {
      $('a.media').media({width:700, height:900});
  });
</script>